version: 0.2

phases:
  pre_build:
    commands:
      - aws sts assume-role --role-session-name DeployPipeline --role-arn ${ROLE_ARN} > creds.json
      - export AWS_ACCESS_KEY_ID=`cat creds.json | jq -r '.Credentials.AccessKeyId'`
      - export AWS_SECRET_ACCESS_KEY=`cat creds.json | jq -r '.Credentials.SecretAccessKey'`
      - export AWS_SECURITY_TOKEN=`cat creds.json | jq -r '.Credentials.SessionToken'`
      - $(aws ecr get-login --no-include-email)
      - rm -f creds.json
  build:
    commands:
      - docker build -t ${ECR_ARN}:latest .
      - export TAG=`TZ='Asia/Tokyo' date --date "@\`echo ${CODEBUILD_START_TIME} | sed 's|...$||'\`" '+%Y%m%d%H%M%S'`
      - docker tag ${ECR_ARN}:latest ${ECR_ARN}:${TAG}
  post_build:
    commands:
      - docker push ${ECR_ARN}:${TAG}
      - docker push ${ECR_ARN}:latest
